include:
  - file: "master-gitlab-ci.yml"
    project: "automation/pudge"
    ref: "master"
variables:
  ARTIFACT_DIR: "artifacts"
  CHAPTER_NAME: "vendor"
  CODEBASE_VERSION: "latest"
  CODE_BASE: "PHP"
  CONFIG_PATH: ".env"
  DEPLOYMENT_NAME: ""
  DEPLOY_DEV: "EC2"
  DEPLOY_PROD: "EC2"
  DEPLOY_STG: "EC2"
  FILECOPY: "false"
  FILECOPY_DIR: ""
  FILECOPY_NAME: ""
  HEALTHCHECK: "/"
  MULTIDEPLOY: "false"
  PORT: "80"
  SONAR: "false"
  SQUAD_NAME: "iota"
  UNIT_TEST: "false"